name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"
jojo = "go"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "ywboy.top"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
 routes = [
   { pattern = "docker.ywboy.top", custom_domain = true },
   { pattern = "quay.ywboy.top", custom_domain = true },
   { pattern = "gcr.ywboy.top", custom_domain = true },
   { pattern = "k8s-gcr.ywboy.top", custom_domain = true },
   { pattern = "k8s.ywboy.top", custom_domain = true },
   { pattern = "ghcr.ywboy.top", custom_domain = true },
   { pattern = "cloudsmith.ywboy.top", custom_domain = true },
 ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.ywboy.top", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
